version: '3.8'

services:
  dev_blockchain_node_1:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    restart: on-failure
    command: python3 src/main.py -p 5001
    ports:
      - 5001:5001
    volumes:
      - ./src:/blockchain/src

  dev_blockchain_node_2:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    restart: on-failure
    command: python3 src/main.py -p 5002
    ports:
      - 5002:5002
    volumes:
      - ./src:/blockchain/src

  prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: on-failure
    ports:
      - 5000:5000

  tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    restart: on-failure
    command: python3 -m unittest discover -s tests -p 'test_*.py'
    volumes:
      - .:/blockchain
    container_name: blockchain_coin_tests
