version: '3.8'

services:
  blockchain:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    restart: on-failure
    command: python3 src/main.py
    ports:
      - 5000:5000
    volumes:
      - .:/blockchain

  tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    restart: on-failure
    command: python3 -m unittest tests.test_chain_creation
    volumes:
      - .:/blockchain
    container_name: blockchain_coin_tests

