# This workflow will build and push a Python application to an Azure Web App when a commit is pushed to your default branch.
#
# This workflow assumes you have already created the target Azure App Service web app.
# For instructions see https://docs.microsoft.com/en-us/azure/app-service/quickstart-python?tabs=bash&pivots=python-framework-flask
#
# To configure this workflow:
#
# 1. Download the Publish Profile for your Azure Web App. You can download this file from the Overview page of your Web App in the Azure Portal.
#    For more information: https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel#generate-deployment-credentials
#
# 2. Create a secret in your repository named AZURE_WEBAPP_PUBLISH_PROFILE, paste the publish profile contents as the value of the secret.
#    For instructions on obtaining the publish profile see: https://docs.microsoft.com/azure/app-service/deploy-github-actions#configure-the-github-secret
#
# 3. Change the value for the AZURE_WEBAPP_NAME. Optionally, change the PYTHON_VERSION environment variables below.
#
# For more information on GitHub Actions for Azure: https://github.com/Azure/Actions
# For more information on the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples

name: Deploy node to VM


env:
  WEBAPP_NAME: blockchain
  PYTHON_VERSION: '3.8.13'

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    
      - name: Wait for unit tests to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-tests
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: unit_tests
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
    
      - name: Wait for black to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-format
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: black_format
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: blockchain-node
          path: |
            . 
            !venv/

  deploy:
    runs-on: ubuntu-latest
    environment: production
    needs: tests

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: blockchain-node
          path: .

      - run: ls -l /home/runner/work/blockchain/blockchain
      - run: echo "host" ${{ secrets.VM_HOST }}
      - run: echo "user" ${{ secrets.VM_USER }}

      - name: SSH Server Deploy
        # You may pin to the exact commit or the version.
        # uses: kostya-ten/ssh-server-deploy@e0deb814bc458a68b61f6597a865d096e33eb586
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
        with:
          host: ${{ secrets.VM_HOST }}
          user: ${{ secrets.VM_USER }}
          pass: ${{ secrets.VM_PWD }}
          first_ssh: |
            pwd ; ls -la ;
            if test -f "chmod +x ${HOME}/blockchain/end_prod.sh ; ${HOME}/blockchain/end_prod.sh"; then ${HOME}/blockchain/end_prod.sh; fi ;
            rm -rf ~/blockchain/ && mkdir -p ~/blockchain
          scp: |
            /home/runner/work/blockchain/blockchain/* => /home/gth_group/blockchain/
          last_ssh: |
            echo "Starting node" ; pwd ; ls -la ;
            cd blockchain ; pwd ; ls -la ; chmod +x ./prod.sh ; ./prod.sh && echo "Node started"
