name: Code formatter

on:
  push:
    branches:
      - main
      - prod
      - dev
  pull_request:
    branches:
      - main
      - prod
      - dev

  workflow_dispatch:

permissions:
  contents: read

jobs:
  black_format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - run: |
          python --version
       
      - name: Install black
        run: |
          python -m pip uninstall black -y
          python -m pip uninstall click -y
          python -m pip install --upgrade click==8.0.4  --no-input
          python -m pip install black==22.6.0  --no-input
          python -m black . --check
          black . --check

      - name: Black Code Formatter
        uses: piotrpawlaczek/python-blacken@v22.3.0
        with:
          path: .
          only-check: yes

