name: Build and push Docker image upon release

on:
  # Build and push Docker images *only* for releases.
  release:
    types: [published] # , created, edited
  push: # remove me
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  push_to_registry_v2:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: gamestradehub/blockchain-coin_prod:latest